[package]
name = "entiffen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imagepipe = "0.4"
image = "0.23.14"
rawloader = "0.36.3"
structopt = "0.3.21"
rayon = "1.5.0"
anyhow = "1.0.40"
